---
abstract: 'try to make global variables a little safer'
author:
  - 'Flavio Poletti <flavio [at] polettix [dot] it>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: vars-global
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  version: 0
version: v0.0.4
